/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Qwerty model module.
 * @module model/Qwerty
 * @version 1.0.0
 */
class Qwerty {
    /**
     * Constructs a new <code>Qwerty</code>.
     * @alias module:model/Qwerty
     * @param qTitle {String} 
     */
    constructor(qTitle) { 
        
        Qwerty.initialize(this, qTitle);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, qTitle) { 
        obj['qTitle'] = qTitle;
    }

    /**
     * Constructs a <code>Qwerty</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Qwerty} obj Optional instance to populate.
     * @return {module:model/Qwerty} The populated <code>Qwerty</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Qwerty();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('qTitle')) {
                obj['qTitle'] = ApiClient.convertToType(data['qTitle'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Qwerty.prototype['_id'] = undefined;

/**
 * @member {String} qTitle
 */
Qwerty.prototype['qTitle'] = undefined;






export default Qwerty;

